# Generated by Django 5.2.6 on 2025-09-06 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyhabits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 12, 26, 5, 811613, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
            preserve_default=False,
        ),
    ]
