# Generated by Django 5.2.6 on 2025-09-06 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyhabits', '0002_aspiration_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspiration',
            name='published_at',
        ),
        migrations.AddField(
            model_name='aspiration',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 12, 29, 32, 29018, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
        ),
    ]
