# Generated by Django 5.2.6 on 2025-09-06 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyhabits', '0003_remove_aspiration_published_at_aspiration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspiration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
    ]
